### ISSUE TITLE
Email editor: Plus button not visible on small screens

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2042]
## Description
On smaller screens, the plus button that is to the left of the editor content gets cropped away outside of the viewport.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go to any project (or create one)
3. Click "Create activity"
4. Click "Create email"
5. Go to the "Compose" tab
6. Write something in the first paragraph and hover the paragraph to see the buttons
7. Make window less than 1200 pixels wide (if left hand side menu bar is collapsed)

### Expected Behaviour
The plus button should still be fully visible somehow, e.g. by shrinking the content or collapsing the right-hand-side pane.

### Actual Behaviour
The plus button (and eventually the dotted button as well) are hidden behind the navbar.

### Too narrow
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/4b72313f-ca51-4bcd-b99d-29a49da8dc35)

### Even narrower
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/c35cfe51-64e8-4eb2-a3c4-aadb97a107e0)

**Comment by DaleLuce** [comment]
looking into this

**Comment by Bagera** [comment]
I have been investigating a bit.

This is an issue if the page loads when over 1034px wide and is then narrowed. If it loads at narrower widths the buttons will be on the right and not disappear.

We can work around the issue by adding some margin.
```css
@media (min-width: 651px) {
  .content-editor {
    margin-inline-start: 64px;
  }
}
@media (min-width: 1210px) {
  .content-editor {
    margin-inline-start: 64px;
  }
}
@media (min-width: 651px) {
  .codex-editor--narrow .ce-toolbar__actions {
    right: 100%; /* Places the controls on the left again even if the screen was small when loading*/
  }
}
```
Under 651px the button will change to float on top of the blocks and work. If there is a way to change this media query we could also solve it by making the buttons float until the screen is 1210px wide.
