### ISSUE TITLE
Setup lyra configuration

### ISSUE THREAD

**Issue by xela1601** [zetkin/app.zetkin.org#2810]
## Description

A user should be able to use [lyra](https://github.com/zetkin/lyra) to add translations/i18n to zetkin.
Therefore a [lyra config(`lyra.yaml`)](https://github.com/zetkin/lyra/blob/255964fea40f827af7e713509d1d03304ba752b9/README.md?plain=1#L67-L83) file needs to be created in the zetkin repository's root (see below)

## Estimated size (S, M, L)

I think this issue is S because it only involves adding a yaml file to the project

## Requirements

- [ ] the `lyra.yaml` file exists in the repository's root

## Possible implementations

```yaml
projects:
  - path: . # relative path to project in repo
    messages:
      format: ts
      path: src # relative path of messages folder relative from above project path
    translations:
      path: src/locale # relative path of translations folder relative from above project path
    languages: # list of language codes supported in the project
      - sv
      - de
      - en
      - nn
      - da
    base_branch: main # optional default to 'main'
```
